// highlights.js
export const highlightedPlayers = {
  "NYY": ["Aaron Judge", "Gerrit Cole", "Carlos Rodón", "Ryan McMahon", "Cam Schlittler", "Jasson Domínguez", "George Lombard Jr."],
  "BOS": ["Roman Anthony", "Garrett Crochet", "Ranger Suárez", "Aroldis Chapman"],
  "TOR": ["Vladimir Guerrero Jr.", "George Springer", "Kevin Gausman", "Dylan Cease", "Max Scherzer", "Shane Bieber", "Trey Yesavage", "Kazuma Okamota"],
  "TAM": ["Junior Caminero", "Shane McClanahan"],
  "BAL": ["Pete Alonso", "Gunnar Henderson", "Adley Rutschman", "Jackson Holliday", "Colton Cowser", "Samuel Basallo"],
  "CLE": ["José Ramírez", "Chase DeLauter", "Tanner Bibee", "Gavin Williams", "Joey Cantillo", "Parker Messick", "Slade Cecconi", "Cade Smith"],
  "CHW": ["Munetaka Murakami"],
  "DET": ["Tarik Skubal", "Framber Valdez", "Casey Mize", "Jack Flaherty", "Justin Verlander", "Jackson Jobe", "Reese Olson", "Troy Melton", "Kevin McGonigle"],
  "MIN": [],
  "KCR": ["Bobby Witt Jr.", "Maikel Garcia", "Vinnie Pasquantino", "Jac Caglianone", "Carter Jensen", "Cole Ragans"],
  "HOU": ["Yordan Alvarez", "Jeremy Peña", "Jose Altuve", "Hunter Brown", "Josh Hader"],
  "ATH": ["Nick Kurtz", "Jacob Wilson", "Shea Langeliers", "Brent Rooker", "Lawrence Butler"],
  "LAA": ["Mike Trout"],
  "SEA": ["Bryan Woo", "Logan Gilbert", "Luis Castillo", "George Kirby", "Emerson Hancock", "Bryce Miller", "Cal Raleigh", "Julio Rodríguez", "Andrés Muñoz"],
  "TEX": ["Jacob deGrom", "Nathan Eovaldi", "MacKenzie Gore", "Jack Leiter", "Kumar Rocker", "Corey Seager", "Andrew McCutchen"],
  "ATL": ["Ronald Acuña Jr", "Michael Harris II", "Drake Baldwin", "Chris Sale", "Didier Fuentes", "Spencer Strider", "Spencer Schwellenbach"],
  "MIA": ["Agustín Ramírez", "Sandy Alcantara", "Eury Pérez"],
  "NYM": ["Juan Soto", "Francisco Lindor", "Bo Bichette", "Luis Robert Jr", "Carson Benge", "Freddy Peralta", "Nolan McLean"],
  "PHI": ["Kyle Schwarber", "Trea Turner", "Bryce Harper", "Justin Crawford", "Zack Wheeler", "Cristopher Sánchez", "Jesús Luzardo", "Aaron Nola", "Andrew Painter", "Jhoan Duran"],
  "WAS": ["Cade Cavalli", "Dylan Crews", "James Wood"],
  "CIN": ["Elly De La Cruz", "Hunter Greene", "Chase Burns", "Sal Stewart", "Nick Lodolo", "Andrew Abbott", "Rhett Lowder", "Noelvi Marte"],
  "MIL": ["Jackson Chourio", "Brice Turang", "Brandon Woodruff", "Jacob Misiorowski", "Quinn Priester", "Abner Uribe"],
  "CHC": ["Pete Crow-Armstrong", "Cade Horton", "Matthew Boyd", "Justin Steele"],
  "PIT": ["Paul Skenes", "Mitch Keller", "Braxton Ashcraft", "Bubba Chandler", "Jared Jones", "Konnor Griffin"],
  "STL": ["JJ Wetherholt", "Jordan Walker", "Matthew Liberatore", "Dustin May"],
  "LAD": ["Shohei Ohtani", "Mookie Betts", "Freddie Freeman", "Kyle Tucker", "Andy Pages", "Yoshinobu Yamamoto", "Tyler Glasnow", "Emmet Sheehan", "Roki Sasaki", "Justin Wrobleski", "Blake Snell", "Edwin Díaz"],
  "SDP": ["Fernando Tatis Jr.", "Manny Machado", "Jackson Merrill", "Xander Bogaerts", "Jake Cronenworth", "Mason Miller", "Michael King", "Nick Pivetta"],
  "COL": [],
  "ARI": ["Zac Gallen", "Geraldo Perdomo", "Ketel Marte", "Corbin Carroll", "Ryne Nelson", "Brandon Pfaadt", "Corbin Burnes", "Merrill Kelly"],
  "SFG": ["Bryce Eldridge", "Logan Webb", "Robbie Ray"]
};
